//! Minimal uncompressed PFH5 writer for packs generated by the manager.
//!
//! The layout matches the original manager's `writeStartGamePack`: a mod-type
//! pack without dependencies, without per-file timestamps (flag `0x40` unset)
//! and with an `is_compressed = 0` byte in every index entry.
use crate::{Error, Result, storage};
use std::{collections::HashSet, path::Path};

const MAGIC: &[u8; 4] = b"PFH5";
/// Pack type "mod" with no extra header flags.
const FLAGS: u32 = 3;
/// The original manager writes this constant into the header timestamp slot.
const TIMESTAMP: u32 = 0x7fff_ffff;

fn word(value: usize) -> Result<u32> {
    u32::try_from(value)
        .map_err(|_| Error::Pack(crate::message!("pack is too large", "pack слишком большой")))
}

/// Encodes files into PFH5 bytes, keeping the order given by the caller.
///
/// The original start-game writer does not sort entries itself, so callers
/// provide them in the order they should appear in the index.
pub fn encode(files: &[(&str, &[u8])]) -> Result<Vec<u8>> {
    let mut names = HashSet::with_capacity(files.len());
    let mut index = Vec::new();
    let mut payload_size = 0usize;
    for (name, content) in files {
        if name.is_empty() || name.contains('\0') {
            return Err(Error::Pack(crate::message!(
                "invalid packed file name",
                "неверное имя файла в pack"
            )));
        }
        // The game resolves packed paths case-insensitively, so two spellings
        // of one path would make the result depend on index order.
        if !names.insert(name.to_lowercase()) {
            return Err(Error::Pack(crate::message!(
                "duplicate packed file: {}",
                "повторяющийся файл в pack: {}",
                name
            )));
        }
        index.extend_from_slice(&word(content.len())?.to_le_bytes());
        index.push(0);
        index.extend_from_slice(name.as_bytes());
        index.push(0);
        payload_size = payload_size.checked_add(content.len()).ok_or_else(|| {
            Error::Pack(crate::message!("pack is too large", "pack слишком большой"))
        })?;
    }
    let mut bytes = Vec::with_capacity(28 + index.len() + payload_size);
    bytes.extend_from_slice(MAGIC);
    for value in [
        FLAGS,
        0,
        0,
        word(files.len())?,
        word(index.len())?,
        TIMESTAMP,
    ] {
        bytes.extend_from_slice(&value.to_le_bytes());
    }
    bytes.extend_from_slice(&index);
    for (_, content) in files {
        bytes.extend_from_slice(content);
    }
    Ok(bytes)
}

/// Writes a pack atomically so the game never sees a half-written file.
pub fn write(path: &Path, files: &[(&str, &[u8])]) -> Result<()> {
    storage::atomic_write(path, &encode(files)?)
}
